name: End-to-End tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run cypress:run
      
      - name: Cypress Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome HTML Report
          path: cypress/reports/html

      - name: Job Summary
        if: always()
        run: |
          echo "### Cypress Test Results" >> $GITHUB_STEP_SUMMARY
          echo "#### Test Run Summary" >> $GITHUB_STEP_SUMMARY
          echo "Total tests run: $(grep -o 'tests run' cypress/reports/html/index.html | awk '{print $3}')" >> $GITHUB_STEP_SUMMARY
          echo "Total failures: $(grep -o 'failed' cypress/reports/html/index.html | awk '{print $3}')" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### [View Full Cypress Report](cypress/reports/html/index.html)" >> $GITHUB_STEP_SUMMARY
 